import React,{useEffect,useMemo,useState} from 'react';
import {CalendarDays,CheckCircle2,Clock3,CreditCard,IndianRupee,Plus,X} from 'lucide-react';
import ReservationService from '../services/ReservationService';
import CarService from '../services/CarService';
import '../styles/CarBookings.css';

const CarBookings=({user})=>{const[bookings,setBookings]=useState([]),[cars,setCars]=useState([]),[loading,setLoading]=useState(true),[formOpen,setFormOpen]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState({type:'',text:''}),[form,setForm]=useState({car_id:'',order_date:'',payment_mode:''});
 const load=async()=>{setLoading(true);try{const[a,b]=await Promise.all([ReservationService.getAllReservations(),CarService.getAllCars()]);setCars(b.data||[]);const map=new Map((b.data||[]).map(c=>[c.id,c]));setBookings((a.data||[]).filter(x=>x.user_id===user?.id).map(x=>({...x,car:map.get(x.car_id)})))}catch(e){setMessage({type:'error',text:'Unable to load your bookings right now.'})}finally{setLoading(false)}};useEffect(()=>{if(user)load()},[user]);
 const selectedCar=cars.find(c=>String(c.id)===form.car_id);const availableCars=useMemo(()=>cars.filter(c=>c.availability),[cars]);const change=e=>setForm(f=>({...f,[e.target.name]:e.target.value}));
 const submit=async e=>{e.preventDefault();if(!selectedCar)return setMessage({type:'error',text:'Please choose a vehicle.'});setSaving(true);setMessage({type:'',text:''});try{await ReservationService.addReservation({user_id:user.id,car_id:Number(form.car_id),order_date:form.order_date,total_price:Number(selectedCar.price),payment_mode:form.payment_mode,status:'pending'});setMessage({type:'success',text:'Booking request submitted successfully.'});setForm({car_id:'',order_date:'',payment_mode:''});setFormOpen(false);await load()}catch(err){setMessage({type:'error',text:err.response?.data?.message||'Could not submit the reservation.'})}finally{setSaving(false)}};
 const statusClass=s=>String(s||'pending').toLowerCase().replaceAll(' ','-');
 if(loading)return <section className="car-bookings booking-module"><div className="booking-loading">Loading your bookings…</div></section>;
 return <section className="car-bookings booking-module"><header className="module-header"><div><span className="section-kicker">Reservations</span><h1>My car bookings</h1><p>Track your vehicle requests from one place.</p></div><button className="module-primary" onClick={()=>{setFormOpen(v=>!v);setMessage({type:'',text:''})}}>{formOpen?<><X size={16}/> Close</>:<><Plus size={16}/> Book a car</>}</button></header>{message.text&&<div className={`module-message ${message.type}`}><CheckCircle2 size={17}/><span>{message.text}</span></div>}
 {formOpen&&<form className="reservation-card" onSubmit={submit}><div className="reservation-head"><div><span className="section-kicker">New reservation</span><h2>Reserve your next vehicle</h2></div></div><div className="reservation-grid"><label><span>Vehicle</span><select name="car_id" value={form.car_id} onChange={change} required><option value="">Choose an available vehicle</option>{availableCars.map(c=><option key={c.id} value={c.id}>{c.brand||c.make} {c.model} · ₹{Number(c.price||0).toLocaleString('en-IN')}</option>)}</select></label><label><span>Preferred date</span><input type="date" name="order_date" value={form.order_date} onChange={change} min={new Date().toISOString().split('T')[0]} required/></label><label><span>Payment method</span><select name="payment_mode" value={form.payment_mode} onChange={change} required><option value="">Choose payment method</option><option value="upi">UPI</option><option value="credit_card">Credit card</option><option value="debit_card">Debit card</option><option value="net_banking">Net banking</option><option value="cash">Cash at showroom</option></select></label>{selectedCar&&<div className="price-summary"><span><IndianRupee size={15}/> Estimated vehicle price</span><strong>₹{Number(selectedCar.price||0).toLocaleString('en-IN')}</strong><small>Final pricing will be confirmed by the dealership.</small></div>}</div><div className="reservation-actions"><button type="button" className="module-secondary" onClick={()=>setFormOpen(false)}>Cancel</button><button className="module-primary" disabled={saving}>{saving?'Submitting…':<>Submit request <CheckCircle2 size={15}/></>}</button></div></form>}
 <div className="booking-list-head"><div><h2>Recent activity</h2><span>{bookings.length} {bookings.length===1?'booking':'bookings'}</span></div></div>{bookings.length===0?<div className="booking-empty"><div><CalendarDays size={22}/></div><h3>No bookings yet</h3><p>When you reserve a vehicle, its status will appear here.</p><button className="module-primary" onClick={()=>setFormOpen(true)}>Start a booking</button></div>:<div className="booking-list">{bookings.map(b=><article className="booking-row" key={b.id}><div className="booking-car-icon"><Clock3 size={18}/></div><div className="booking-main"><strong>{b.car?`${b.car.brand||b.car.make} ${b.car.model}`:`Vehicle #${b.car_id}`}</strong><span>Booking #{b.id} · {b.order_date?new Date(b.order_date).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'Date pending'}</span></div><div className="booking-price">₹{Number(b.total_price||0).toLocaleString('en-IN')}</div><span className={`booking-status ${statusClass(b.status)}`}>{b.status||'Pending'}</span></article>)}</div>}</section>};export default CarBookings;
