import React, { useEffect, useMemo, useState } from 'react';
import { CarFront, Check, Edit3, Plus, Search, Trash2, X } from 'lucide-react';
import CarService from '../services/CarService';
import '../styles/FeaturedVehicles.css';

const emptyCar = () => ({ model:'', brand:'', year:new Date().getFullYear(), price:'', availability:true, image:'' });
const fallbackImage = 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80';

const FeaturedVehicles = ({ setActiveSection, user, setSelectedCar, isManageMode=false }) => {
  const [cars,setCars]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('all'); const [editing,setEditing]=useState(null); const [form,setForm]=useState(emptyCar()); const [saving,setSaving]=useState(false); const [confirming,setConfirming]=useState(null);
  const canManage = ['employee','supervisor'].includes(String(user?.role||'').toLowerCase()); const isSupervisor=String(user?.role||'').toLowerCase()==='supervisor';
  const fetchCars=async()=>{setLoading(true);setError('');try{const response=await CarService.getAllCars();setCars((response.data||[]).map(car=>({...car,price:Number(car.price||0)})));}catch(err){setError(err.response?.data?.message||'Unable to load vehicles right now.');}finally{setLoading(false)}};
  useEffect(()=>{fetchCars()},[]);
  const filtered=useMemo(()=>cars.filter(car=>{const text=`${car.brand} ${car.model} ${car.year}`.toLowerCase();return text.includes(query.toLowerCase())&&(filter==='all'||(filter==='available'?!!car.availability:!car.availability));}),[cars,query,filter]);
  const openAdd=()=>{setForm(emptyCar());setEditing({mode:'add'});setError('')}; const openEdit=car=>{setForm({model:car.model||'',brand:car.brand||'',year:car.year||new Date().getFullYear(),price:car.price||'',availability:!!car.availability,image:car.image||''});setEditing(car)};
  const save=async e=>{e.preventDefault();setSaving(true);setError('');try{const payload={...form,year:Number(form.year),price:Number(form.price)};if(editing?.mode==='add')await CarService.addCar(payload);else await CarService.updateCar(editing.id,payload);setEditing(null);await fetchCars()}catch(err){setError(err.response?.data?.message||'Could not save vehicle.');}finally{setSaving(false)}};
  const remove=async()=>{if(!confirming)return;setSaving(true);try{await CarService.deleteCar(confirming.id);setConfirming(null);await fetchCars()}catch(err){setError(err.response?.data?.message||'Could not remove vehicle.')}finally{setSaving(false)}};
  const select=(car,target)=>{setSelectedCar?.(car);setActiveSection?.(target)};
  if(loading)return <div className="vehicle-page"><div className="vehicle-skeleton-grid">{[1,2,3,4].map(i=><div className="vehicle-skeleton" key={i}/>)}</div></div>;
  return <section className="vehicle-page">
    <header className="vehicle-header"><div><span className="section-kicker">{isManageMode?'Operations':'Catalogue'}</span><h1>{isManageMode?'Vehicle management':'Explore vehicles'}</h1><p>{isManageMode?'Keep the showroom catalogue accurate and ready for customers.':'Compare models, check availability and choose what happens next.'}</p></div>{canManage&&<button className="vehicle-primary" onClick={openAdd}><Plus size={17}/> Add vehicle</button>}</header>
    {error&&<div className="vehicle-alert"><span>{error}</span><button onClick={()=>setError('')}><X size={15}/></button></div>}
    <div className="vehicle-toolbar"><div className="vehicle-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search brand, model or year…" aria-label="Search vehicles"/></div><div className="vehicle-filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All <span>{cars.length}</span></button><button className={filter==='available'?'active':''} onClick={()=>setFilter('available')}>Available <span>{cars.filter(c=>c.availability).length}</span></button><button className={filter==='unavailable'?'active':''} onClick={()=>setFilter('unavailable')}>Unavailable <span>{cars.filter(c=>!c.availability).length}</span></button></div></div>
    <div className="vehicle-grid">{filtered.length?filtered.map(car=><article className="vehicle-card" key={car.id}><div className="vehicle-image-wrap"><img src={car.image||fallbackImage} alt={`${car.brand} ${car.model}`} onError={e=>{e.currentTarget.src=fallbackImage}}/><span className={`vehicle-status ${car.availability?'available':'unavailable'}`}><i/>{car.availability?'Available':'Unavailable'}</span></div><div className="vehicle-body"><div className="vehicle-title"><div><span>{car.brand}</span><h3>{car.model}</h3></div><strong>₹{Number(car.price||0).toLocaleString('en-IN')}</strong></div><div className="vehicle-meta"><span>{car.year}</span><span>•</span><span>DriveEase catalogue</span></div><div className="vehicle-actions">{user?.role==='customer'&&<><button className="vehicle-secondary" disabled={!car.availability} onClick={()=>select(car,'testdrive')}>Test drive</button><button className="vehicle-primary small" onClick={()=>select(car,'bookings')}>Book now</button></>}{canManage&&<button className="icon-action" onClick={()=>openEdit(car)} aria-label={`Edit ${car.brand} ${car.model}`}><Edit3 size={16}/></button>}{isSupervisor&&<button className="icon-action danger" onClick={()=>setConfirming(car)} aria-label={`Delete ${car.brand} ${car.model}`}><Trash2 size={16}/></button>}</div></div></article>):<div className="vehicle-empty"><div><CarFront size={25}/></div><h3>No vehicles found</h3><p>Try a different search or filter.</p></div>}</div>
    {editing&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><form className="vehicle-modal" onSubmit={save}><div className="modal-head"><div><span className="section-kicker">Vehicle details</span><h2>{editing.mode==='add'?'Add vehicle':'Edit vehicle'}</h2></div><button type="button" className="modal-close" onClick={()=>setEditing(null)}><X size={18}/></button></div><div className="modal-grid"><label>Brand<input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})} required/></label><label>Model<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})} required/></label><label>Year<input type="number" min="1900" max="2100" value={form.year} onChange={e=>setForm({...form,year:e.target.value})} required/></label><label>Price (₹)<input type="number" min="0" step="1" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/></label><label className="full">Image URL<input value={form.image} onChange={e=>setForm({...form,image:e.target.value})} placeholder="https://…"/></label><label className="availability-toggle"><input type="checkbox" checked={form.availability} onChange={e=>setForm({...form,availability:e.target.checked})}/><span><strong>Available for booking</strong><small>Show this vehicle to customers</small></span></label></div><div className="modal-actions"><button type="button" className="vehicle-secondary" onClick={()=>setEditing(null)}>Cancel</button><button type="submit" className="vehicle-primary" disabled={saving}>{saving?'Saving…':<><Check size={16}/> Save changes</>}</button></div></form></div>}
    {confirming&&<div className="modal-backdrop"><div className="confirm-modal"><div className="confirm-icon"><Trash2 size={21}/></div><h2>Remove this vehicle?</h2><p>This will remove <strong>{confirming.brand} {confirming.model}</strong> from the catalogue.</p><div className="modal-actions"><button className="vehicle-secondary" onClick={()=>setConfirming(null)}>Cancel</button><button className="danger-button" onClick={remove} disabled={saving}>{saving?'Removing…':'Remove vehicle'}</button></div></div></div>}
  </section>;
};
export default FeaturedVehicles;
