import React,{useEffect,useMemo,useState} from 'react';
import {CalendarDays,CarFront,CheckCircle2,Clock3,MapPin,Wrench} from 'lucide-react';
import LocationService from '../services/LocationService';import ServiceRequestService from '../services/ServiceRequestService';import CarService from '../services/CarService';import '../styles/ServiceBookings.css';
const serviceOptions=[['Oil Change',1499,'Routine oil and filter service'],['Tire Rotation',999,'Rotation and basic tyre inspection'],['Brake Inspection',799,'Brake system safety inspection'],['General Maintenance',2999,'Multi-point vehicle maintenance']];
const ServiceBooking=({user})=>{const[locations,setLocations]=useState([]),[vehicles,setVehicles]=useState([]),[form,setForm]=useState({serviceType:'',location_id:'',service_date:'',time:'',car_id:'',description:'',cost:'0'}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState({type:'',text:''});
 useEffect(()=>{(async()=>{try{const[a,b]=await Promise.all([LocationService.getAllLocations(),CarService.getAllCars()]);setLocations(a.data||[]);setVehicles((b.data||[]).filter(c=>c.availability))}catch(e){setMessage({type:'error',text:'We could not load service options. Please refresh and try again.'})}finally{setLoading(false)}})()},[]);
 const chosenService=serviceOptions.find(x=>x[0]===form.serviceType);const chosenCar=vehicles.find(c=>String(c.id)===form.car_id);const today=new Date().toISOString().split('T')[0];const change=e=>{const{name,value}=e.target;setForm(f=>({...f,[name]:value,cost:name==='serviceType'?(serviceOptions.find(x=>x[0]===value)?.[1]||0):f.cost}))};
 const submit=async e=>{e.preventDefault();setSaving(true);setMessage({type:'',text:''});try{await ServiceRequestService.addService({car_id:Number(form.car_id),location_id:Number(form.location_id),service_date:`${form.service_date}T${form.time}:00`,description:`${form.serviceType}: ${form.description}`,cost:Number(form.cost)});setMessage({type:'success',text:'Service request submitted. Our team will contact you to confirm the appointment.'});setForm({serviceType:'',location_id:'',service_date:'',time:'',car_id:'',description:'',cost:'0'})}catch(err){setMessage({type:'error',text:err.response?.data?.message||'We could not book this service. Please try again.'})}finally{setSaving(false)}};
 if(loading)return <div className="service-page"><div className="service-card">Loading service options…</div></div>;
 return <section className="service-page"><header className="service-header"><div><span className="section-kicker">Vehicle care</span><h1>Book a service</h1><p>Tell us what your vehicle needs and we’ll take care of the rest.</p></div><div className="service-badge"><Wrench size={17}/><span><strong>Expert care</strong><small>Service at a DriveEase showroom</small></span></div></header>{message.text&&<div className={`service-message ${message.type}`}><CheckCircle2 size={18}/><span>{message.text}</span></div>}
 <form className="service-layout" onSubmit={submit}><div className="service-card"><div className="service-step"><b>01</b><div><h2>What does your vehicle need?</h2><p>Choose the closest service.</p></div></div><div className="service-options">{serviceOptions.map(([name,cost,desc])=><button type="button" key={name} className={form.serviceType===name?'selected':''} onClick={()=>setForm(f=>({...f,serviceType:name,cost:String(cost)}))}><span className="service-option-icon"><Wrench size={16}/></span><span><strong>{name}</strong><small>{desc}</small></span><em>₹{cost.toLocaleString('en-IN')}</em></button>)}</div></div>
 <div className="service-card"><div className="service-step"><b>02</b><div><h2>Select your vehicle</h2><p>We’ll attach the request to this vehicle.</p></div></div><div className="service-field"><label htmlFor="svc-car"><CarFront size={14}/> Vehicle</label><select id="svc-car" name="car_id" value={form.car_id} onChange={change} required><option value="">Choose a vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.brand||v.make} {v.model} · {v.year}</option>)}</select></div>{chosenCar&&<div className="service-selected"><strong>{chosenCar.brand||chosenCar.make} {chosenCar.model}</strong><span>Ready for service</span></div>}</div>
 <div className="service-card"><div className="service-step"><b>03</b><div><h2>Choose location & time</h2><p>Pick a convenient appointment.</p></div></div><div className="service-field"><label htmlFor="svc-location"><MapPin size={14}/> Service location</label><select id="svc-location" name="location_id" value={form.location_id} onChange={change} required><option value="">Choose a showroom</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}{l.address?` · ${l.address}`:''}</option>)}</select></div><div className="service-two-col"><div className="service-field"><label htmlFor="svc-date"><CalendarDays size={14}/> Date</label><input id="svc-date" type="date" name="service_date" min={today} value={form.service_date} onChange={change} required/></div><div className="service-field"><label htmlFor="svc-time"><Clock3 size={14}/> Time</label><input id="svc-time" type="time" name="time" value={form.time} onChange={change} required/></div></div></div>
 <div className="service-card"><div className="service-step"><b>04</b><div><h2>Tell us more</h2><p>Optional details help our technicians prepare.</p></div></div><div className="service-field"><label htmlFor="svc-description">Notes</label><textarea id="svc-description" name="description" value={form.description} onChange={change} rows="4" maxLength="500" placeholder="Describe an issue or anything you want us to check…"/><small className="char-count">{form.description.length}/500</small></div>{chosenService&&<div className="cost-summary"><span>Estimated starting price</span><strong>₹{chosenService[1].toLocaleString('en-IN')}</strong><small>Final price may change after inspection.</small></div>}</div>
 <div className="service-submit"><div><strong>Ready to book?</strong><span>We’ll confirm the appointment with you.</span></div><button className="service-primary" disabled={saving||!form.serviceType||!form.car_id}>{saving?'Booking…':<>Book service <CheckCircle2 size={16}/></>}</button></div></form></section>};export default ServiceBooking;
