import React,{useEffect,useMemo,useState} from 'react';
import {CheckCircle2,Edit3,KeyRound,Plus,RefreshCw,Search,ShieldCheck,UserCheck,UserX,X} from 'lucide-react';
import StaffService from '../services/StaffService';
import '../styles/StaffManagement.css';
const blank={name:'',email:'',phone:'',password:''};
const StaffManagement=()=>{const[staff,setStaff]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[query,setQuery]=useState(''),[modal,setModal]=useState(null),[form,setForm]=useState(blank),[message,setMessage]=useState({type:'',text:''});
 const load=async()=>{setLoading(true);try{const r=await StaffService.getStaff();setStaff(r.data?.staff||[])}catch(e){setMessage({type:'error',text:e.response?.data?.message||'Unable to load staff.'})}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>staff.filter(s=>`${s.name} ${s.email} ${s.phone}`.toLowerCase().includes(query.toLowerCase())),[staff,query]);
 const submit=async e=>{e.preventDefault();setSaving(true);setMessage({type:'',text:''});try{if(modal.mode==='add'){await StaffService.createEmployee(form);setMessage({type:'success',text:'Employee account created successfully.'})}else{await StaffService.updateEmployee(modal.employee.id,{name:form.name,phone:form.phone});setMessage({type:'success',text:'Employee details updated successfully.'})}setModal(null);setForm(blank);await load()}catch(err){setMessage({type:'error',text:err.response?.data?.message||'Could not save employee.'})}finally{setSaving(false)}};
 const toggle=async employee=>{setSaving(true);try{await StaffService.setStatus(employee.id,!Boolean(employee.is_active));setMessage({type:'success',text:`${employee.name} is now ${employee.is_active?'inactive':'active'}.`});await load()}catch(err){setMessage({type:'error',text:err.response?.data?.message||'Could not change employee status.'})}finally{setSaving(false)}};
 const openEdit=e=>{setForm({name:e.name,email:e.email,phone:e.phone,password:''});setModal({mode:'edit',employee:e})};const openAdd=()=>{setForm(blank);setModal({mode:'add'})};
 return <section className="staff-page"><header className="staff-header"><div><span className="section-kicker">Administration</span><h1>Staff management</h1><p>Create and manage dealership employee access securely.</p></div><div className="staff-header-actions"><button className="staff-refresh" onClick={load}><RefreshCw size={15}/> Refresh</button><button className="staff-primary" onClick={openAdd}><Plus size={16}/> Add employee</button></div></header>{message.text&&<div className={`staff-message ${message.type}`}><CheckCircle2 size={17}/><span>{message.text}</span></div>}<div className="staff-overview"><div><UserCheck size={18}/><span><strong>{staff.filter(s=>s.is_active).length}</strong><small>Active employees</small></span></div><div><UserX size={18}/><span><strong>{staff.filter(s=>!s.is_active).length}</strong><small>Inactive employees</small></span></div><div><ShieldCheck size={18}/><span><strong>{staff.filter(s=>s.role==='supervisor').length}</strong><small>Supervisors</small></span></div></div><div className="staff-toolbar"><div className="staff-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search staff by name, email or phone…"/></div></div><div className="staff-card">{loading?<div className="staff-empty">Loading staff…</div>:filtered.length?<div className="staff-list">{filtered.map(s=><article className="staff-row" key={s.id}><div className="staff-avatar">{s.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><div className="staff-main"><strong>{s.name}</strong><span>{s.email} · {s.phone}</span></div><span className={`staff-role ${s.role}`}>{s.role}</span><span className={`staff-state ${s.is_active?'active':'inactive'}`}>{s.is_active?'Active':'Inactive'}</span><div className="staff-actions">{s.role==='employee'&&<><button onClick={()=>openEdit(s)} title="Edit employee"><Edit3 size={15}/></button><button onClick={()=>toggle(s)} disabled={saving} title={s.is_active?'Deactivate employee':'Activate employee'}>{s.is_active?<UserX size={15}/>:<UserCheck size={15}/>}</button></>}</div></article>)}</div>:<div className="staff-empty"><div><Search size={20}/></div><h3>No staff found</h3><p>Try another search.</p></div>}</div>
 {modal&&<div className="staff-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><form className="staff-modal" onSubmit={submit}><div className="staff-modal-head"><div><span className="section-kicker">{modal.mode==='add'?'New team member':'Employee profile'}</span><h2>{modal.mode==='add'?'Add employee':'Edit employee'}</h2></div><button type="button" onClick={()=>setModal(null)}><X size={18}/></button></div><div className="staff-form-grid"><label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required minLength="2" maxLength="100"/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></label><label className="full">Work email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} disabled={modal.mode==='edit'} required/></label>{modal.mode==='add'&&<label className="full">Temporary password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} minLength="8" required/><small><KeyRound size={12}/> Give this password to the employee securely. Never store it in GitHub.</small></label>}<div className="staff-role-box"><ShieldCheck size={16}/><span><strong>Employee access</strong><small>Employees can process operational work but cannot manage staff or vehicles.</small></span></div></div><div className="staff-modal-actions"><button type="button" className="staff-secondary" onClick={()=>setModal(null)}>Cancel</button><button className="staff-primary" disabled={saving}>{saving?'Saving…':<>{modal.mode==='add'?'Create employee':'Save changes'} <CheckCircle2 size={15}/></>}</button></div></form></div>}</section>};export default StaffManagement;
