import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CarFront, CheckCircle2, Clock3, MapPin, MessageSquare } from 'lucide-react';
import CarService from '../services/CarService';
import LocationService from '../services/LocationService';
import TestDriveService from '../services/TestDriveService';

const timeSlots={1:'09:00 AM – 09:30 AM',2:'09:30 AM – 10:00 AM',3:'10:00 AM – 10:30 AM',4:'10:30 AM – 11:00 AM',5:'11:00 AM – 11:30 AM',6:'11:30 AM – 12:00 PM',7:'01:00 PM – 01:30 PM',8:'01:30 PM – 02:00 PM',9:'02:00 PM – 02:30 PM',10:'02:30 PM – 03:00 PM'};
const TestDrive=({user,selectedCar})=>{const [cars,setCars]=useState([]),[locations,setLocations]=useState([]),[form,setForm]=useState({car:'',location:'',date:'',slot:'',comments:''}),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[success,setSuccess]=useState(''),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const[a,b]=await Promise.all([CarService.getAllCars(),LocationService.getAllLocations()]);setCars(a.data||[]);setLocations(b.data||[]);}catch(e){setError('We could not load booking options. Please refresh and try again.')}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(selectedCar?.id)setForm(f=>({...f,car:String(selectedCar.id)}))},[selectedCar]);
 const availableCars=useMemo(()=>cars.filter(c=>c.availability),[cars]); const chosenCar=cars.find(c=>String(c.id)===form.car); const chosenLocation=locations.find(l=>String(l.id)===form.location);
 const change=e=>setForm(f=>({...f,[e.target.name]:e.target.value}));
 const submit=async e=>{e.preventDefault();setSubmitting(true);setError('');setSuccess('');try{await TestDriveService.bookTestDrive({user_id:user.id,car_id:Number(form.car),location_id:Number(form.location),preferred_date:form.date,slot_number:Number(form.slot),status:'pending',comments:form.comments||'Test drive request'});setSuccess('Your test drive request has been submitted. We’ll contact you to confirm the appointment.');setForm({car:'',location:'',date:'',slot:'',comments:''})}catch(err){setError(err.response?.data?.message||'We could not schedule your test drive. Please try again.')}finally{setSubmitting(false)}};
 if(loading)return <div className="booking-page"><div className="booking-card loading-card">Loading your booking options…</div></div>;
 return <section className="booking-page"><header className="booking-header"><div><span className="section-kicker">Experience the vehicle</span><h1>Schedule a test drive</h1><p>Choose a vehicle, showroom and time that works for you.</p></div><div className="booking-badge"><CalendarDays size={17}/><span><strong>30 minutes</strong><small>Typical appointment</small></span></div></header>{success&&<div className="booking-success"><CheckCircle2 size={19}/><span><strong>Request received</strong><small>{success}</small></span></div>}{error&&<div className="booking-error">{error}</div>}
 <form className="booking-layout" onSubmit={submit}><div className="booking-card"><div className="form-section-title"><span>01</span><div><h2>Choose your vehicle</h2><p>Select an available model.</p></div></div><div className="booking-field"><label htmlFor="td-car"><CarFront size={14}/> Vehicle</label><select id="td-car" name="car" value={form.car} onChange={change} required><option value="">Select a vehicle</option>{availableCars.map(c=><option key={c.id} value={c.id}>{c.brand} {c.model} · ₹{Number(c.price||0).toLocaleString('en-IN')}</option>)}</select></div>{chosenCar&&<div className="selection-summary"><strong>{chosenCar.brand} {chosenCar.model}</strong><span>{chosenCar.year} · Available</span></div>}</div>
 <div className="booking-card"><div className="form-section-title"><span>02</span><div><h2>Pick a showroom</h2><p>Choose where you’d like to drive.</p></div></div><div className="booking-field"><label htmlFor="td-location"><MapPin size={14}/> Showroom</label><select id="td-location" name="location" value={form.location} onChange={change} required><option value="">Select a showroom</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}{l.address?` · ${l.address}`:''}</option>)}</select></div>{chosenLocation&&<div className="selection-summary"><strong>{chosenLocation.name}</strong><span>{chosenLocation.phone||'Showroom support available'}</span></div>}</div>
 <div className="booking-card"><div className="form-section-title"><span>03</span><div><h2>Choose date & time</h2><p>Appointments are available during showroom hours.</p></div></div><div className="date-field booking-field"><label htmlFor="td-date"><CalendarDays size={14}/> Date</label><input id="td-date" type="date" name="date" value={form.date} onChange={change} min={new Date().toISOString().split('T')[0]} required/></div><div className="slot-label"><Clock3 size={14}/> Time slot</div><div className="slot-grid">{Object.entries(timeSlots).map(([n,label])=><button type="button" key={n} className={form.slot===n?'selected':''} onClick={()=>setForm(f=>({...f,slot:n}))}>{label}</button>)}</div><input tabIndex={-1} className="slot-validation" value={form.slot} onChange={()=>{}} required aria-label="Selected time slot"/></div>
 <div className="booking-card"><div className="form-section-title"><span>04</span><div><h2>Anything we should know?</h2><p>Optional details for your appointment.</p></div></div><div className="booking-field"><label htmlFor="td-comments"><MessageSquare size={14}/> Notes</label><textarea id="td-comments" name="comments" value={form.comments} onChange={change} rows="4" maxLength="500" placeholder="Questions, accessibility needs or preferences…"/><small>{form.comments.length}/500</small></div></div>
 <div className="booking-submit"><div><strong>Ready to drive?</strong><span>Your request will be reviewed by our team.</span></div><button className="booking-primary" disabled={submitting||!form.slot}>{submitting?'Scheduling…':<>Schedule test drive <CheckCircle2 size={16}/></>}</button></div></form></section>};export default TestDrive;
