const Service = require("../models/serviceModel");
exports.addService=async(req,res)=>{try{const user_id=req.user.id;const{car_id,location_id,service_date,description,cost}=req.body;if(!car_id||!location_id||!service_date||!description||cost===undefined)return res.status(400).json({message:"Vehicle, location, date, description and cost are required"});const numericCost=Number(cost);if(!Number.isFinite(numericCost)||numericCost<0)return res.status(400).json({message:"Invalid service cost"});const serviceId=await Service.addService({user_id,car_id,location_id,service_date,description:String(description).trim().slice(0,1000),cost:numericCost,status:"pending"});res.status(201).json({message:"Service booked successfully",serviceId})}catch(error){console.error("Service create error:",error);res.status(500).json({message:"Unable to book service"})}};
exports.getAllServices=async(req,res)=>{try{res.status(200).json(await Service.getAllServices())}catch(error){console.error("Service list error:",error);res.status(500).json({message:"Unable to load services"})}};
exports.getServiceById=async(req,res)=>{try{const service=await Service.getServiceById(req.params.id);if(!service)return res.status(404).json({message:"Service not found"});if(req.user.role==='customer'&&Number(service.user_id)!==Number(req.user.id))return res.status(403).json({message:"Access denied"});res.status(200).json(service)}catch(error){console.error("Service detail error:",error);res.status(500).json({message:"Unable to load service"})}};
exports.getServicesByUserId=async(req,res)=>{try{const userId=Number(req.params.userId);if(!Number.isInteger(userId))return res.status(400).json({message:"Invalid user"});if(req.user.role==='customer'&&userId!==req.user.id)return res.status(403).json({message:"Access denied"});res.status(200).json(await Service.getServicesByUserId(userId))}catch(error){console.error("User service history error:",error);res.status(500).json({message:"Unable to load service history"})}};
exports.getServicesByLocationId=async(req,res)=>{try{res.status(200).json(await Service.getServicesByLocationId(req.params.locationId))}catch(error){console.error("Location service error:",error);res.status(500).json({message:"Unable to load location services"})}};
exports.updateServiceStatus=async(req,res)=>{try{const{status}=req.body;if(!["pending","in_progress","completed"].includes(status))return res.status(400).json({message:"Invalid service status"});const affectedRows=await Service.updateServiceStatus(req.params.id,status);if(!affectedRows)return res.status(404).json({message:"Service not found"});res.status(200).json({message:"Service status updated successfully"})}catch(error){console.error("Service status error:",error);res.status(500).json({message:"Unable to update service status"})}};
exports.updateService=async(req,res)=>{try{const{location_id,service_date,description,cost,status}=req.body;if(!location_id||!service_date||!description||cost===undefined||!status)return res.status(400).json({message:"All service details are required"});const affectedRows=await Service.updateService(req.params.id,{location_id,service_date,description,cost,status});if(!affectedRows)return res.status(404).json({message:"Service not found"});res.status(200).json({message:"Service updated successfully"})}catch(error){console.error("Service update error:",error);res.status(500).json({message:"Unable to update service"})}};
exports.deleteService=async(req,res)=>{try{const affectedRows=await Service.deleteService(req.params.id);if(!affectedRows)return res.status(404).json({message:"Service not found"});res.status(200).json({message:"Service deleted successfully"})}catch(error){console.error("Service delete error:",error);res.status(500).json({message:"Unable to delete service"})}};
